
document.addEventListener("DOMContentLoaded", function() {
    const data = [
    {
        "Quel est le nom du projet ? ": "archA",
        "Qui est porteur du projet ?": "Société Française d'Acoustique",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "European Acoustics Association",
        "Qui est représentant du projet ?": "Société Française d'Acoustique",
        "Quel est le montant alloué aux projet ? ": 87500,
        "Quelle est la durée du projet ? ": "30 Mois",
        "Quelle est le périmètre  du projet ? ": "Information-Documentation, Information scientifique et technique, Science Ouverte",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "Comptes Rendus de l'Académie des sciences",
        "Qui est porteur du projet ?": "Académie des Sciences\n",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Mathdoc - Cellule de coordination documentaire nationale pour les mathématiques",
        "Qui est représentant du projet ?": "Académie des Sciences",
        "Quel est le montant alloué aux projet ? ": 90000,
        "Quelle est la durée du projet ? ": "12 Mois",
        "Quelle est le périmètre  du projet ? ": "Documentation, Information scientifique et technique, Science ouverte",
        "Quels outils/technologies seront avancés ? ": "Open Journal System",
        "D'où proviennent les technologies avancés ? ": "Public Knowledge Project "
    },
    {
        "Quel est le nom du projet ? ": "Dispositif d’Accompagnement pour le Développement de l’Accès Ouvert (DADAO)",
        "Qui est porteur du projet ?": "Aix Marseille Université - Open Edition Center",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Université de Caen Normandie - CERTIC;Université de Caen Normandie - Pôle document numérique MRSH,Métopes",
        "Qui est représentant du projet ?": "OpenEdition",
        "Quel est le montant alloué aux projet ? ": "184 612,61 €",
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Information scientifique et technique ",
        "Quels outils/technologies seront avancés ? ": "Open Edition , Lodel ",
        "D'où proviennent les technologies avancés ? ": " Centre pour l'édition électronique ouverte, Open Edition "
    },
    {
        "Quel est le nom du projet ? ": "Développements Éditoriaux du Centre Mersenne pour l'Ouverture de la Science  ( MÉDOS)",
        "Qui est porteur du projet ?": "MathDoc ",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Aucun",
        "Qui est représentant du projet ?": "MathDoc ",
        "Quel est le montant alloué aux projet ? ": 192000,
        "Quelle est la durée du projet ? ": "30 mois",
        "Quelle est le périmètre  du projet ? ": "Science Ouverte, Information scientifique et technique ",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "Collection Humanités numériques : livres et données en open access ( DH-Lidoa)",
        "Qui est porteur du projet ?": "MESHS - Maison européenne des sciences de l’homme et de la société",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "PUS - Presses Universitaires du Septentrion",
        "Qui est représentant du projet ?": "Janis Monchet ",
        "Quel est le montant alloué aux projet ? ": 38664,
        "Quelle est la durée du projet ? ": "54 mois",
        "Quelle est le périmètre  du projet ? ": "Science Ouverte, Information scientifique et technique ",
        "Quels outils/technologies seront avancés ? ": "Open Edition ",
        "D'où proviennent les technologies avancés ? ": " Centre pour l'édition électronique ouverte"
    },
    {
        "Quel est le nom du projet ? ": "Dissemin",
        "Qui est porteur du projet ?": "ENS PSL - École normale supérieure PSL",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Télécom Paris\nCAPSH - Comité pour l'Accessibilité aux Publications en Sciences et Humanités",
        "Qui est représentant du projet ?": " Pierre Senellart, Antoine Amarilli",
        "Quel est le montant alloué aux projet ? ": 124200,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Archive ouverte et Archivistiques",
        "Quels outils/technologies seront avancés ? ": "Dissemin ",
        "D'où proviennent les technologies avancés ? ": "CAPSH (Comité pour l'Accessibilité aux Publications en Sciences et Humanités) "
    },
    {
        "Quel est le nom du projet ? ": "Fabula 2020 : plateforme ouverte de la recherche en littérature ",
        "Qui est porteur du projet ?": "THALIM - Théorie et histoire des arts et des littératures de la modernité",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "CELLF - Centre d'étude de la langue et des littératures françaises,\nUniversité de Lausanne",
        "Qui est représentant du projet ?": "Esther Demoulin ",
        "Quel est le montant alloué aux projet ? ": 175400,
        "Quelle est la durée du projet ? ": "30 mois",
        "Quelle est le périmètre  du projet ? ": "Information Documentation, Visualisation de données ",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": " FAIREST - FAIR environnement pour l’édition structurée ",
        "Qui est porteur du projet ?": "METOPES - Méthodes et outils pour l’édition structurée",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Infrastructure de recherche\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "CLEO - Open Edition Center,PKP - Public knowledge project,OPERAS",
        "Qui est représentant du projet ?": "METOPES",
        "Quel est le montant alloué aux projet ? ": 227059.2,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Information Documentation - Édition numérique ",
        "Quels outils/technologies seront avancés ? ": "Métopes ",
        "D'où proviennent les technologies avancés ? ": "MRSH de Caen. "
    },
    {
        "Quel est le nom du projet ? ": " HALOWIN HAL Open Workflows and Interoperability ",
        "Qui est porteur du projet ?": "CCSD - Centre pour la communication scientifique directe",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Infrastructure de recherche\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Aucun ",
        "Qui est représentant du projet ?": "CCSD",
        "Quel est le montant alloué aux projet ? ": 79150,
        "Quelle est la durée du projet ? ": "33 mois",
        "Quelle est le périmètre  du projet ? ": "Édition numérique, Publications",
        "Quels outils/technologies seront avancés ? ": "HAL, Episciences, PeerCommunity In",
        "D'où proviennent les technologies avancés ? ": "Hal,CCSD, Peer Community "
    },
    {
        "Quel est le nom du projet ? ": " HNSO Huma-Num Science Ouverte ",
        "Qui est porteur du projet ?": "HUMA-NUM - Humanités Numériques",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Infrastructure de recherche\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Aucun ",
        "Qui est représentant du projet ?": "Mélanie Bunel, Jean-Luc Minel, Stéphane Pouyllau, Nicolas Sauret",
        "Quel est le montant alloué aux projet ? ": 287712,
        "Quelle est la durée du projet ? ": "24 mois",
        "Quelle est le périmètre  du projet ? ": "Publications, Données",
        "Quels outils/technologies seront avancés ? ": "ISIDORE,NAKALA",
        "D'où proviennent les technologies avancés ? ": "Huma-Num."
    },
    {
        "Quel est le nom du projet ? ": "I-FAIR IR",
        "Qui est porteur du projet ?": "CLEO - Open Edition Center",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Infrastructure de recherche",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "METOPES - Méthodes et outils pour l’édition structurée",
        "Qui est représentant du projet ?": "Open Edition Center ",
        "Quel est le montant alloué aux projet ? ": 298193.4,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Information Scientifique et technique, Droit ",
        "Quels outils/technologies seront avancés ? ": "Open Edition, Metopes ",
        "D'où proviennent les technologies avancés ? ": " Centre pour l'édition électronique ouverte"
    },
    {
        "Quel est le nom du projet ? ": " MetoTaxa Adaptation de la chaîne Métopes à l’édition de taxonomie ",
        "Qui est porteur du projet ?": "Muséum national d'histoire naturelle",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "METOPES - Méthodes et outils pour l’édition structurée",
        "Qui est représentant du projet ?": "Open Edition Center ",
        "Quel est le montant alloué aux projet ? ": 89064,
        "Quelle est la durée du projet ? ": "15 mois",
        "Quelle est le périmètre  du projet ? ": "Interopérabilité des données ",
        "Quels outils/technologies seront avancés ? ": "Métopes, TaxPub, DarwinCore ",
        "D'où proviennent les technologies avancés ? ": "Open Edition,Plazi, Biodiversity Information Standards "
    },
    {
        "Quel est le nom du projet ? ": "OPEN-STICS",
        "Qui est porteur du projet ?": "Centre INRAE Centre-siège",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Editions QUAE,CIRAD - Centre de coopération internationale en recherche agronomique pour le développement",
        "Qui est représentant du projet ?": "INRAE ",
        "Quel est le montant alloué aux projet ? ": 20933,
        "Quelle est la durée du projet ? ": "24 mois",
        "Quelle est le périmètre  du projet ? ": "Édition numérique ",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "OpenMetaPaper",
        "Qui est porteur du projet ?": "Muséum national d'histoire naturelle",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Infrastructure de recherche\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "PNDB - Pôle National de Données de Biodiversité",
        "Qui est représentant du projet ?": "Muséum national d'histoire naturelle",
        "Quel est le montant alloué aux projet ? ": 172000,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Donnée de la recherche ",
        "Quels outils/technologies seront avancés ? ": "MetaShARK",
        "D'où proviennent les technologies avancés ? ": "PNDB"
    },
    {
        "Quel est le nom du projet ? ": "ORA-HdF",
        "Qui est porteur du projet ?": "Université de Lille",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "MESHS - Maison européenne des sciences de l’homme et de la société, CLEO - Open Edition Center",
        "Qui est représentant du projet ?": "Université de Lille",
        "Quel est le montant alloué aux projet ? ": 70000,
        "Quelle est la durée du projet ? ": "34 mois",
        "Quelle est le périmètre  du projet ? ": "Édition numérique, Open Access",
        "Quels outils/technologies seront avancés ? ": "Lodel",
        "D'où proviennent les technologies avancés ? ": "Open Edition "
    },
    {
        "Quel est le nom du projet ? ": "PA-BMSAP",
        "Qui est porteur du projet ?": "Société d'anthropologie de Paris",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Aucun",
        "Qui est représentant du projet ?": "Société d'anthropologie de Paris",
        "Quel est le montant alloué aux projet ? ": 20000,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Open Access",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": " Peer Community in Des communautés de chercheurs au service de la validation de preprints ",
        "Qui est porteur du projet ?": "Centre INRAE Occitanie-Montpellier",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "CCSD",
        "Qui est représentant du projet ?": "Centre INRAE Occitanie-Montpellier",
        "Quel est le montant alloué aux projet ? ": 140400,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Science Ouverte,  évaluation de la recherche ",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "PhSc-SO-2020",
        "Qui est porteur du projet ?": "Université de Lorraine",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "CLEO - Open Edition Center,Cairn.info",
        "Qui est représentant du projet ?": "Université de Lorraine",
        "Quel est le montant alloué aux projet ? ": 12000,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Open Access",
        "Quels outils/technologies seront avancés ? ": "Cairn,Open Edition ",
        "D'où proviennent les technologies avancés ? ": " Bibliothèque nationale de France, Humensis, De Boeck, La Découverte, Madrigall et Érès,  Centre pour l'édition électronique ouverte"
    },
    {
        "Quel est le nom du projet ? ": " REGOSO REvues du Grand Ouest : accompagnement gradué et mutualisé vers la Science Ouverte ",
        "Qui est porteur du projet ?": "Université Rennes 2",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Aucun",
        "Qui est représentant du projet ?": "MSHB",
        "Quel est le montant alloué aux projet ? ": 90000,
        "Quelle est la durée du projet ? ": "30 mois",
        "Quelle est le périmètre  du projet ? ": "Édition scientifique, Science ouverte,numérique ",
        "Quels outils/technologies seront avancés ? ": "Stylo",
        "D'où proviennent les technologies avancés ? ": "Huma-Num"
    },
    {
        "Quel est le nom du projet ? ": " REPÈRES REnforcer les PEpinières de REvues et la dynamique de la Science ouverte ",
        "Qui est porteur du projet ?": "Université Jean Moulin - Lyon 3",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Université Lumière - Lyon 2\nMSH - LSE - Maison des Sciences de l'Homme Lyon Saint-Etienne, UT2 - Université Toulouse - Jean Jaurès, Maison des Sciences de l'Homme de Dijon, METOPES - Méthodes et outils pour l’édition structurée, CLEO - Open Edition Center",
        "Qui est représentant du projet ?": "Université Jean Moulin - Lyon 3",
        "Quel est le montant alloué aux projet ? ": 157648.55,
        "Quelle est la durée du projet ? ": "38 mois",
        "Quelle est le périmètre  du projet ? ": "Open Access, numérique ",
        "Quels outils/technologies seront avancés ? ": "NC ( probablement Open Edition, Lodel ou Métopes à la vue des partenaires)",
        "D'où proviennent les technologies avancés ? ": "NC "
    },
    {
        "Quel est le nom du projet ? ": "S2O/SMAI Passage en \"Subscribe to Open\" des revues de la SMAI ",
        "Qui est porteur du projet ?": "SMAI - Société de mathématiques appliquées et industrielles",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Aucun",
        "Qui est représentant du projet ?": "SMAI - Société de mathématiques appliquées et industrielles",
        "Quel est le montant alloué aux projet ? ": 74051,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Open Access",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "SciPost-CX",
        "Qui est porteur du projet ?": "Stichting SciPost",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "1ère édition - Appel à projets Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Aucun",
        "Qui est représentant du projet ?": "Stichting SciPost",
        "Quel est le montant alloué aux projet ? ": 44412,
        "Quelle est la durée du projet ? ": "24 mois",
        "Quelle est le périmètre  du projet ? ": "Open Access, Numérique ",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "ARCHES",
        "Qui est porteur du projet ?": "Institut national de recherches archéologiques préventives (Inrap)",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Métopes",
        "Qui est représentant du projet ?": "Inrap ",
        "Quel est le montant alloué aux projet ? ": 189000,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "Métopes",
        "D'où proviennent les technologies avancés ? ": "Open Edition "
    },
    {
        "Quel est le nom du projet ? ": "Canal-U Science Ouverte sur les Vidéos",
        "Qui est porteur du projet ?": "Fondation Maison des sciences de l'homme",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Aucun",
        "Qui est représentant du projet ?": "Fondation Maison des sciences de l'homme",
        "Quel est le montant alloué aux projet ? ": 100000,
        "Quelle est la durée du projet ? ": "24 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "DOI/RGAA",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "E-Études Créoles",
        "Qui est porteur du projet ?": "Aix-Marseille Université - Laboratoire Parole et Langage",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Aucun",
        "Qui est représentant du projet ?": "Aix-Marseille Université - Laboratoire Parole et Langage",
        "Quel est le montant alloué aux projet ? ": 16200,
        "Quelle est la durée du projet ? ": "30 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "Open Edition ",
        "D'où proviennent les technologies avancés ? ": " Centre pour l'édition électronique ouverte"
    },
    {
        "Quel est le nom du projet ? ": "ÉdulOA",
        "Qui est porteur du projet ?": "Université de Lorraine",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Aucun",
        "Qui est représentant du projet ?": "Université de Lorraine ",
        "Quel est le montant alloué aux projet ? ": 95133,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "FORBEROSE",
        "Qui est porteur du projet ?": "Cergy Paris Université",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Universidade Nova de Lisboa",
        "Qui est représentant du projet ?": "Cergy Paris Université",
        "Quel est le montant alloué aux projet ? ": 80000,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "Bérose",
        "D'où proviennent les technologies avancés ? ": "Laboratoire d’anthropologie et d’institution de la culture, Institut interdisciplinaire de l’anthropologie du contemporain (LAHIC-IIAC ; CNRS/EHESS/Ministère de la Culture)"
    },
    {
        "Quel est le nom du projet ? ": "Geodesic",
        "Qui est porteur du projet ?": "MathDoc (CNRS et UGA)",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale\n",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Réseau National des Bibliothèques de Mathématiques (RNBM)",
        "Qui est représentant du projet ?": "MathDoc (CNRS et UGA)",
        "Quel est le montant alloué aux projet ? ": "170 279 €",
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "MarginaliAS",
        "Qui est porteur du projet ?": "Académie des sciences",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "MathDoc (CNRS et UGA)",
        "Qui est représentant du projet ?": "Académie des sciences",
        "Quel est le montant alloué aux projet ? ": "54 000 €",
        "Quelle est la durée du projet ? ": "24 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "Mémoires européennes du Goulag",
        "Qui est porteur du projet ?": "Institut national d’études démographiques",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale ",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "CERCEC,GED Condorcet Strasbourg",
        "Qui est représentant du projet ?": "Institut national d’études démographiques",
        "Quel est le montant alloué aux projet ? ": "44 950 €",
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "MetoSTeM",
        "Qui est porteur du projet ?": "Muséum national d’Histoire naturelle",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "CNRS - Inist\nMétopes",
        "Qui est représentant du projet ?": "Muséum national d’Histoire naturelle",
        "Quel est le montant alloué aux projet ? ": "89 046 €",
        "Quelle est la durée du projet ? ": "25 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "Métopes",
        "D'où proviennent les technologies avancés ? ": "Open Edition"
    },
    {
        "Quel est le nom du projet ? ": "Mir@bel2022",
        "Qui est porteur du projet ?": "Sciences Po Lyon",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale ",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Abes\nCairn\nDOAJ\nEDP Sciences\nENTPE\nMSH Dijon\nSciencesPo Grenoble\nErudit\nOpenEdition\nPersée\nPresses Universitaire de Caen\nMathDoc (CNRS et UGA)\nUniversité Lyon 3 ",
        "Qui est représentant du projet ?": "Sciences Po Lyon",
        "Quel est le montant alloué aux projet ? ": "80 000 €",
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "OpenAgroécologie",
        "Qui est porteur du projet ?": "INRAE",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux ",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Cirad , Quae",
        "Qui est représentant du projet ?": "INRAE ",
        "Quel est le montant alloué aux projet ? ": "140 000 €",
        "Quelle est la durée du projet ? ": "30 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "OPEN-AUDIOLIVRES",
        "Qui est porteur du projet ?": "Éditions Quæ",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Aucun",
        "Qui est représentant du projet ?": "Éditions Quæ",
        "Quel est le montant alloué aux projet ? ": "45 000 €",
        "Quelle est la durée du projet ? ": "12 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "OPEN-SHS",
        "Qui est porteur du projet ?": "Université Paris Lumières",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": " Plateforme ou structure éditoriale ",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Université de Poitiers\nCNRS\nFNRS\nUniversité Paris 8 Saint-Denis\nUniversité Paris- Nanterre",
        "Qui est représentant du projet ?": "Université Paris Lumières",
        "Quel est le montant alloué aux projet ? ": "37 476 €",
        "Quelle est la durée du projet ? ": "16 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "OUJ 2024",
        "Qui est porteur du projet ?": "Université de Bordeaux",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux ",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "INRAE\nUniversité de Lorraine",
        "Qui est représentant du projet ?": "Université de Bordeaux",
        "Quel est le montant alloué aux projet ? ": "200 000 €",
        "Quelle est la durée du projet ? ": "34 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "Open Journal System",
        "D'où proviennent les technologies avancés ? ": "Public Knowledge Project "
    },
    {
        "Quel est le nom du projet ? ": "PAYS",
        "Qui est porteur du projet ?": "Université de Paris ",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Association des Assistants et Internes en Neurologie (ANAINF)",
        "Qui est représentant du projet ?": "Université de Paris ",
        "Quel est le montant alloué aux projet ? ": "48 253 €",
        "Quelle est la durée du projet ? ": "24 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "OPUS",
        "D'où proviennent les technologies avancés ? ": "Université Paris Cité"
    },
    {
        "Quel est le nom du projet ? ": "PEARS",
        "Qui est porteur du projet ?": "Université Côte d’Azur",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": " Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Aucun",
        "Qui est représentant du projet ?": "Université Côte d’Azur",
        "Quel est le montant alloué aux projet ? ": "77 000 €",
        "Quelle est la durée du projet ? ": "24 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "PEREPIGA",
        "Qui est porteur du projet ?": "Association Epiga",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": " Contenus éditoriaux ou associant plusieurs projets éditoriaux ",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Société freelance Reinie Erné\nUniversité de Lorraine",
        "Qui est représentant du projet ?": "Association Epiga ",
        "Quel est le montant alloué aux projet ? ": "10 500 €",
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "PRESS",
        "Qui est porteur du projet ?": "Université de Caen Normandie",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux ",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Métopes\nOpenEdition\nENC-CTHS",
        "Qui est représentant du projet ?": "Université de Caen Normandie ",
        "Quel est le montant alloué aux projet ? ": "200 000 €",
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "Open Edition ",
        "D'où proviennent les technologies avancés ? ": " Centre pour l'édition électronique ouverte"
    },
    {
        "Quel est le nom du projet ? ": "Ques2comSO",
        "Qui est porteur du projet ?": "Université de Lorraine",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Cairn",
        "Qui est représentant du projet ?": "Université de Lorraine",
        "Quel est le montant alloué aux projet ? ": "15 000 €",
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "Cairn",
        "D'où proviennent les technologies avancés ? ": " Bibliothèque nationale de France, Humensis, De Boeck, La Découverte, Madrigall et Érès,  Centre pour l'édition électronique ouverte"
    },
    {
        "Quel est le nom du projet ? ": "RAPIDO",
        "Qui est porteur du projet ?": "ENS de Lyon",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": " Plateforme ou structure éditoriale ",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "CNRS-Inist\nÉcole française de Rome\nÉcole française d'Athènes\nAbes",
        "Qui est représentant du projet ?": "ENS de Lyon",
        "Quel est le montant alloué aux projet ? ": "90 000 €",
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "ReScience C",
        "Qui est porteur du projet ?": "Inria",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme ou structure éditoriale",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Aucun ",
        "Qui est représentant du projet ?": "Inria",
        "Quel est le montant alloué aux projet ? ": "14 256 €",
        "Quelle est la durée du projet ? ": "16 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "Open Journal",
        "D'où proviennent les technologies avancés ? ": "Open Edition "
    },
    {
        "Quel est le nom du projet ? ": "SO PUR",
        "Qui est porteur du projet ?": "SAIC Presses universitaires de Rennes",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": " Plateforme ou structure éditoriale ",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Métopes\nOpenEdition\nMaison des Sciences de l’Homme en Bretagne\nSCD Université Rennes 2\nSCD Université Rennes 1",
        "Qui est représentant du projet ?": "SAIC Presses universitaires de Rennes",
        "Quel est le montant alloué aux projet ? ": "199 952 €",
        "Quelle est la durée du projet ? ": "32 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "Métopes, Open Édition",
        "D'où proviennent les technologies avancés ? ": "Open Edition  Centre pour l'édition électronique ouverte"
    },
    {
        "Quel est le nom du projet ? ": "SOCL",
        "Qui est porteur du projet ?": "Société Mathématique de France",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Aucun",
        "Qui est représentant du projet ?": "Société Mathématique de France",
        "Quel est le montant alloué aux projet ? ": 20000,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "SOEA",
        "Qui est porteur du projet ?": "UAR 3336 Afrique au Sud du Sahara",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": " Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "UAR 3137 Centre français des études éthiopiennes\nUMR 5115 Les Afriques dans le monde\nUMR 8171 Institut des mondes africains\nGIS Études africaines en France\nOpenEdition\nMétopes",
        "Qui est représentant du projet ?": "UAR 3336 Afrique au Sud du Sahara",
        "Quel est le montant alloué aux projet ? ": "154 541 €",
        "Quelle est la durée du projet ? ": "45 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "Métopes, Open Édition",
        "D'où proviennent les technologies avancés ? ": "Open Edition  Centre pour l'édition électronique ouverte"
    },
    {
        "Quel est le nom du projet ? ": "THOLOS",
        "Qui est porteur du projet ?": "École française d'Athènes",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": " Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "ArScAn",
        "Qui est représentant du projet ?": "École française d'Athènes",
        "Quel est le montant alloué aux projet ? ": 43011,
        "Quelle est la durée du projet ? ": "24 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique et Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "TOPEDITOR",
        "Qui est porteur du projet ?": "Casa de Velázquez",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": " Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "EHESS\nOpenEdition\nMétopes\nHuma-Num",
        "Qui est représentant du projet ?": "Casa de Velázquez",
        "Quel est le montant alloué aux projet ? ": "44 729 €",
        "Quelle est la durée du projet ? ": "24 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "Métopes, Open Édition",
        "D'où proviennent les technologies avancés ? ": "Open Edition  Centre pour l'édition électronique ouverte"
    },
    {
        "Quel est le nom du projet ? ": "Volcanica",
        "Qui est porteur du projet ?": "Institut Terre et Environnement de Strasbourg",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": " Plateforme ou structure éditoriale ",
        "Dans quelle édition FNSO se trouve ce projet ?": "2ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Volcanica Editorial Committee\nFondation des Presses Universitaire de Strasbourg",
        "Qui est représentant du projet ?": "Institut Terre et Environnement de Strasbourg",
        "Quel est le montant alloué aux projet ? ": "45 000 €",
        "Quelle est la durée du projet ? ": "16 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "COOPÈRES",
        "Qui est porteur du projet ?": "Lyon III - Université Jean Moulin - Lyon 3",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme de diffusion",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "UBx - Université de Bordeaux,METOPES - Méthodes et outils pour l’édition structurée,Université de Liège,UMR Héritages - Héritages : Patrimoine(s), Culture(s), Création(s),CLEO - Open Edition Center,Persée",
        "Qui est représentant du projet ?": "Lyon III - Université Jean Moulin - Lyon 3",
        "Quel est le montant alloué aux projet ? ": 145800,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "Métopes, Open Édition",
        "D'où proviennent les technologies avancés ? ": "Open Edition  Centre pour l'édition électronique ouverte"
    },
    {
        "Quel est le nom du projet ? ": "AEnumonline",
        "Qui est porteur du projet ?": "Association d'historiens de l'Est",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "UL - Université de Lorraine",
        "Qui est représentant du projet ?": "Association d'historiens de l'Est",
        "Quel est le montant alloué aux projet ? ": 35720,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "Édisciences",
        "Qui est porteur du projet ?": "CCSD - Centre pour la communication scientifique directe",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "ARDM - Association pour la Recherche en Didactique des Mathématiques,AFITL - Association Française des Instituts de Transport et de Logistique,JTCAM - Journal of Theoretical, Computational and Applied Mechanics",
        "Qui est représentant du projet ?": "CCSD - Centre pour la communication scientifique directe",
        "Quel est le montant alloué aux projet ? ": 35720,
        "Quelle est la durée du projet ? ": "12 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "SciPost-ElDia",
        "Qui est porteur du projet ?": "Stichting SciPost",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": null,
        "Qui est représentant du projet ?": "Stichting SciPost",
        "Quel est le montant alloué aux projet ? ": 35720,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "QUAMÉO",
        "Qui est porteur du projet ?": "AMU - Aix-Marseille Université",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Infrastructure de recherche",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Abes - Agence bibliographique de l'enseignement supérieur",
        "Qui est représentant du projet ?": "AMU - Aix-Marseille Université",
        "Quel est le montant alloué aux projet ? ": 296314,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "NEXTGEN",
        "Qui est porteur du projet ?": "Délégation Alpes du CNRS",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme de diffusion",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": null,
        "Qui est représentant du projet ?": "Délégation Alpes du CNRS",
        "Quel est le montant alloué aux projet ? ": 199146,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "EPISUD-PUV",
        "Qui est porteur du projet ?": "PUV - Presses universitaires de Vincennes",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "LADYSS - Laboratoire Dynamiques Sociales et Recomposition des Espaces",
        "Qui est représentant du projet ?": "PUV - Presses universitaires de Vincennes",
        "Quel est le montant alloué aux projet ? ": 38617,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique & Diffusion ",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "NUM SO",
        "Qui est porteur du projet ?": "PUR - Presses universitaires de Rennes",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "PUM - Presses de l'Université de Montréal",
        "Qui est représentant du projet ?": "PUR - Presses universitaires de Rennes",
        "Quel est le montant alloué aux projet ? ": 67000,
        "Quelle est la durée du projet ? ": "12 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "OPUS",
        "Qui est porteur du projet ?": "EFA - École française d'Athènes",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "ResEFE - Réseau des Écoles françaises à l'étranger",
        "Qui est représentant du projet ?": "EFA - École française d'Athènes",
        "Quel est le montant alloué aux projet ? ": 42552,
        "Quelle est la durée du projet ? ": "24 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "HORTUS",
        "Qui est porteur du projet ?": "MISHA - Maison Interuniverstaire des Sciences de l’Homme – Alsace",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme de diffusion",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "METOPES - Méthodes et outils pour l’édition structurée,CLEO - Open Edition Center",
        "Qui est représentant du projet ?": "MISHA - Maison Interuniverstaire des Sciences de l’Homme – Alsace",
        "Quel est le montant alloué aux projet ? ": 138383,
        "Quelle est la durée du projet ? ": "24 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "Métopes  Open Edition ( au vu des partenaires )",
        "D'où proviennent les technologies avancés ? ": "Open Edition  Centre pour l'édition électronique ouverte"
    },
    {
        "Quel est le nom du projet ? ": "PEPSO-BFC",
        "Qui est porteur du projet ?": "uB - Université de Bourgogne",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme de diffusion",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "UFC - Université de Franche-Comté,Persée",
        "Qui est représentant du projet ?": "uB - Université de Bourgogne",
        "Quel est le montant alloué aux projet ? ": 194380,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Numérique et Juridique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "OpenIFEA",
        "Qui est porteur du projet ?": "IFEA - Institut français d'études anatoliennes - Georges Dumezil",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "EPML - Musée du Louvre",
        "Qui est représentant du projet ?": "IFEA - Institut français d'études anatoliennes - Georges Dumezil",
        "Quel est le montant alloué aux projet ? ": 32268,
        "Quelle est la durée du projet ? ": "12 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "RPN",
        "Qui est porteur du projet ?": "Université de Lorraine",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": null,
        "Qui est représentant du projet ?": "Université de Lorraine",
        "Quel est le montant alloué aux projet ? ": 23386,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "CDS-ODAS",
        "Qui est porteur du projet ?": "Observatoire astronomique de Strasbourg",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Infrastructure de recherche",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": null,
        "Qui est représentant du projet ?": "Observatoire astronomique de Strasbourg",
        "Quel est le montant alloué aux projet ? ": 290779,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "PerVisum",
        "Qui est porteur du projet ?": "INHA - Institut national d'histoire de l'art",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme de diffusion",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "METOPES - Méthodes et outils pour l’édition structurée,CLEO - Open Edition Center",
        "Qui est représentant du projet ?": "INHA - Institut national d'histoire de l'art",
        "Quel est le montant alloué aux projet ? ": 87480,
        "Quelle est la durée du projet ? ": "24 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "Métopes  Open Edition ( au vu des partenaires )",
        "D'où proviennent les technologies avancés ? ": "Open Edition  Centre pour l'édition électronique ouverte"
    },
    {
        "Quel est le nom du projet ? ": "nEpHAL+",
        "Qui est porteur du projet ?": "CCSD - Centre pour la communication scientifique directe",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Infrastructure de recherche",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "Software Heritage,Inria - Institut national de recherche en sciences et technologies du numérique,DARIAH - Digital Research Infrastructure for the Arts and Humanities",
        "Qui est représentant du projet ?": "CCSD - Centre pour la communication scientifique directe",
        "Quel est le montant alloué aux projet ? ": 270000,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "Mir@AO",
        "Qui est porteur du projet ?": "IEP de Lyon - Sciences Po Lyon",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme de diffusion",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "UGA - Université Grenoble Alpes,IEP de Grenoble - Sciences Po Grenoble,ENTPE - École nationale des travaux publics de l'État,MSH Dijon - Maison des Sciences de l'Homme de Dijon",
        "Qui est représentant du projet ?": "IEP de Lyon - Sciences Po Lyon",
        "Quel est le montant alloué aux projet ? ": 99230,
        "Quelle est la durée du projet ? ": "24 mois",
        "Quelle est le périmètre  du projet ? ": "Infrastructure et  écosystème de l'édition et de la publication scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "PRGO",
        "Qui est porteur du projet ?": "Rennes II - Université Rennes 2",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Plateforme de diffusion",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": "NU - Nantes Université,UBO - Université de Bretagne Occidentale,UA - Université d'Angers,UniR - Université de Rennes",
        "Qui est représentant du projet ?": "Rennes II - Université Rennes 2",
        "Quel est le montant alloué aux projet ? ": 42000,
        "Quelle est la durée du projet ? ": "36 mois",
        "Quelle est le périmètre  du projet ? ": "Organisationnel, Diffusion, Politique ",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    },
    {
        "Quel est le nom du projet ? ": "Sharqiyat",
        "Qui est porteur du projet ?": "ifpo - Institut français du Proche-Orient",
        "Dans quel volet(s) de l'appel se trouve le projet ? ": "Contenus éditoriaux ou associant plusieurs projets éditoriaux",
        "Dans quelle édition FNSO se trouve ce projet ?": "3ème édition - Publication et édition scientifiques ouvertes ",
        "Qui est partenaire de ce projet ? ": null,
        "Qui est représentant du projet ?": "ifpo - Institut français du Proche-Orient",
        "Quel est le montant alloué aux projet ? ": 88775,
        "Quelle est la durée du projet ? ": "24 mois",
        "Quelle est le périmètre  du projet ? ": "Publication et édition scientifique",
        "Quels outils/technologies seront avancés ? ": "NC",
        "D'où proviennent les technologies avancés ? ": "NC"
    }
];

    const tableBody = document.getElementById('dataTable').getElementsByTagName('tbody')[0];
    data.forEach(item => {
        const row = tableBody.insertRow();
        Object.keys(item).forEach(key => {
            const cell = row.insertCell();
            cell.textContent = item[key];
        });
    });

    window.filterData = function() {
        const input = document.getElementById('searchInput');
        const filter = input.value.toUpperCase();
        const tr = tableBody.getElementsByTagName('tr');

        for (let i = 0; i < tr.length; i++) {
            let visible = false;
            const td = tr[i].getElementsByTagName('td');
            for (let j = 0; j < td.length; j++) {
                if (td[j].textContent.toUpperCase().indexOf(filter) > -1) {
                    visible = true;
                    break;
                }
            }
            tr[i].style.display = visible ? "" : "none";
        }
    };
});
